#include "+A.h"




void +A::perimetre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--27-1--50ed53b:16deef48622:-8000:00000000000009BA begin
{
}
// section -64--88--27-1--50ed53b:16deef48622:-8000:00000000000009BA end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void +A::+size()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--27-1--50ed53b:16deef48622:-8000:00000000000009C0 begin
{
}
// section -64--88--27-1--50ed53b:16deef48622:-8000:00000000000009C0 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
