#include "adhérent.h"




void adhérent::emprunterLivre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-49f21be0:16e1d144e90:-8000:000000000000151A begin
{
}
// section -64--88-56-1-49f21be0:16e1d144e90:-8000:000000000000151A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void adhérent::rendreLivre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-49f21be0:16e1d144e90:-8000:000000000000151C begin
{
}
// section -64--88-56-1-49f21be0:16e1d144e90:-8000:000000000000151C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
