#include "bibliothèque.h"




void bibliothèque::ajouterAdherent()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-49f21be0:16e1d144e90:-8000:00000000000014C1 begin
{
}
// section -64--88-56-1-49f21be0:16e1d144e90:-8000:00000000000014C1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void bibliothèque::enleverAdherent()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-49f21be0:16e1d144e90:-8000:00000000000014C3 begin
{
}
// section -64--88-56-1-49f21be0:16e1d144e90:-8000:00000000000014C3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void bibliothèque::ajouterDocument()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-49f21be0:16e1d144e90:-8000:00000000000014C5 begin
{
}
// section -64--88-56-1-49f21be0:16e1d144e90:-8000:00000000000014C5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
