#include "emprute.h"




void emprute::pronlongerDateRetour()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-49f21be0:16e1d144e90:-8000:00000000000014DE begin
{
}
// section -64--88-56-1-49f21be0:16e1d144e90:-8000:00000000000014DE end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
